### ISSUE TITLE
ISIP basiert auf  kbv.mio.ueberleitungsbogen: 1.0.0-kommentierung

### ISSUE THREAD

**Issue by patrick-werner** [gematik/spec-ISiP#31]
Nach Release des Ueberleitungsbogens sollte die Abhängigkeit auf das Release Paket angehoben werden.

**Comment by f-peverali** [comment]
Wir könnten sofort auf das neue Package aneheben und/oder nach Ende der Benehemensherstellung: https://simplifier.net/packages/kbv.mio.ueberleitungsbogen/1.0.0-benehmensherstellung

**Comment by f-peverali** [comment]
@patrickwladowska wollen wir zu ISiP hierfür eine TC erstellen?

**Comment by f-peverali** [comment]
Änderungen während Der ÜLB Kommentierung haben keine Auswirkungen auf die Struktur von ISIP -- https://mio.kbv.de/pages/viewpage.action?pageId=152673924

**Comment by f-peverali** [comment]
gelöst mit https://github.com/gematik/spec-ISiP/pull/77/commits/b64166cb2ac0c781a0ab8bc05ab020e00f90ddf2
