### ISSUE TITLE
ISIP Angehöriger

### ISSUE THREAD

**Issue by mmreith** [gematik/spec-ISiP#55]
Warum wird bei der relatedPerson dort ein anderes VS als das preferred genutzt, obwohl dort viele Codes sehr ähnlich sind? Auch die Übersetzung ist z.T. sehr "komisch" und thematisch ist es etwas gemischt..

Wir plädieren daher für das preferred VS, dieses würden wir auch nutzen wollen...

Gruß Max

**Comment by patrick-werner** [comment]
Hallo Max,
danke für deinen Kommentar, das Binding hier ging knapp vorbei. Gemeint war ein required binding auf das Standard VS aus der FHIR Spec. Wird angepasst.

Gruß Patrick
