### ISSUE TITLE
Beispiel für PersonImGesundheitsberuf (Practitioner) ist kein gültiger JSON.

### ISSUE THREAD

**Issue by lsarodnik** [gematik/spec-ISiP#68]
Das Beispiel für PersonImGesundheitsberuf (Practitioner) im IG macht beim JSON Parsen Probleme, weil ein Tab im Display Namen der Qualifikation des Arztes ist. `"display": "	FA Allgemeinmedizin"`

Er könnte durch `\t` ersetzt werden oder entfernt. Ich nehme an, in diesem Fall ist der Tab nicht nötig.

**Comment by f-peverali** [comment]
gelöst mit https://github.com/gematik/spec-ISiP/pull/71
