### ISSUE TITLE
Falscher Link im IG (Practitioner)

### ISSUE THREAD

**Issue by AnsgarHoeper** [gematik/spec-ISiP#88]
Falscher Link im Implementation Guide -> Datenobjekt "Practitioner" (https://simplifier.net/guide/implementierungsleitfadenisik-isip/I-markdown-Datenobjekte-Datenobjekte-PersonImGesundheitsberuf?version=current)

Zu Beginn unter der Überschrift "Interaktionen" wird auf das ISiK Basisprofil verlinkt. Der Link führt jedoch nicht zum angekündigten ISiK Practitioner sondern zum ISiK Related Person.

**Comment by f-peverali** [comment]
@AnsgarHoeper kannst DU hier approven : https://github.com/gematik/spec-ISiP/pull/89 
... ist damit gelöst

**Comment by f-peverali** [comment]
gelöst mit #89
