### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by f-peverali** [gematik/spec-ISiP#95]
siehe https://chat.fhir.org/#narrow/stream/287581-german.2Fisik/topic/.5BISiP.5D.20RelatedPerson/near/398862578

**Comment by simoneOnFhir** [comment]
Bei mir rendert das Profil problemlos: https://simplifier.net/guide/implementierungsleitfadenisik-isip/ImplementationGuide-markdown-Datenobjekte-Datenobjekte-Angehoeriger?version=current
War evtl. ein temporärer HickUp in Simplifier? Wir sollten das Verfahren, "fertige" IGs in Simplifier prerendered zu publishen künftig nutzen, um das zu verhindern: https://docs.fire.ly/projects/Simplifier/implementation_guide/simplifierPublishedGuides.html

**Comment by f-peverali** [comment]
Ich vermute, dass es rendert, weil ich es auch schon in simplifier angepasst habe. Ohne PR wäre es aber beim nächsten sync wieder kaputt. 
Aber danke für den Hinweis auf die Prendering Option, dass sollten wir Diskutieren @MaxMTheilig (FYI)... solche hick-ups beobachte ich tatsächlich und die sorgen immer wieder für "unplanned work"
